import { WorkflowStageDefinition, UserProfile } from '@/types';

export const DEMO_USER_PROFILE: UserProfile = {
  name: 'Prastab Raaj',
  role: 'Project Executive',
  department: 'Office Administration & Contracts',
  environment: 'DEMO',
  avatarInitials: 'PR',
};

export const WORKFLOW_STAGES: WorkflowStageDefinition[] = [
  // ADMIN A: Stages 01–04
  {
    id: '01',
    code: 'TND',
    name: '01 Tender',
    adminGroup: 'ADMIN_A',
    group: 'A',
    groupTitle: 'A — ADMIN WORK DETAILS',
    description: 'Tender documentation, bid submission, EMD processing, and qualification evaluation.',
    phase: 'Phase 2 Module',
  },
  {
    id: '02',
    code: 'LOI',
    name: '02 LOI / LOA',
    adminGroup: 'ADMIN_A',
    group: 'A',
    groupTitle: 'A — ADMIN WORK DETAILS',
    description: 'Letter of Intent and Letter of Award verification, acknowledgement, and administrative logging.',
    phase: 'Phase 2 Module',
  },
  {
    id: '03',
    code: 'ACC',
    name: '03 Acceptance',
    adminGroup: 'ADMIN_A',
    group: 'A',
    groupTitle: 'A — ADMIN WORK DETAILS',
    description: 'Formal contract acceptance submission, executive countersignatures, and authority filing.',
    phase: 'Phase 2 Module',
  },
  {
    id: '04',
    code: 'CPG',
    name: '04 CPG + Agreement',
    adminGroup: 'ADMIN_A',
    group: 'A',
    groupTitle: 'A — ADMIN WORK DETAILS',
    description: 'Contract Performance Guarantee submission, bank verification, stamp duty, and execution of formal contract agreement.',
    phase: 'Phase 2 Module',
  },

  // ADMIN B: Stages 05–09
  {
    id: '05',
    code: 'GTP',
    name: '05 GTP',
    adminGroup: 'ADMIN_B',
    group: 'B',
    groupTitle: 'B — ADMIN WORK DETAILS',
    description: 'Guaranteed Technical Particulars approval, engineering drawing clearances, and client compliance confirmation.',
    phase: 'Phase 3 Module',
  },
  {
    id: '06',
    code: 'PO',
    name: '06 PO',
    adminGroup: 'ADMIN_B',
    group: 'B',
    groupTitle: 'B — ADMIN WORK DETAILS',
    description: 'Purchase Orders issuance to manufacturing vendors, equipment schedules, and milestone tracking.',
    phase: 'Phase 3 Module',
  },
  {
    id: '07',
    code: 'INC',
    name: '07 Inspection Call',
    adminGroup: 'ADMIN_B',
    group: 'B',
    groupTitle: 'B — ADMIN WORK DETAILS',
    description: 'Official factory inspection call to client quality engineers and third-party inspection agency.',
    phase: 'Phase 3 Module',
  },
  {
    id: '08',
    code: 'INO',
    name: '08 Inspection Order',
    adminGroup: 'ADMIN_B',
    group: 'B',
    groupTitle: 'B — ADMIN WORK DETAILS',
    description: 'Inspection authorization order issuance, deputation of inspecting officer, and schedule formalization.',
    phase: 'Phase 3 Module',
  },
  {
    id: '09',
    code: 'JIR',
    name: '09 JIR / Inspection Report',
    adminGroup: 'ADMIN_B',
    group: 'B',
    groupTitle: 'B — ADMIN WORK DETAILS',
    description: 'Joint Inspection Report generation, routine test certificate validation, and quality sign-off.',
    phase: 'Phase 3 Module',
  },

  // ADMIN C: Stages 10–13
  {
    id: '10',
    code: 'DI',
    name: '10 DI / Dispatch Clearance',
    adminGroup: 'ADMIN_C',
    group: 'C',
    groupTitle: 'C — ADMIN',
    description: 'Dispatch Instruction clearance authorization, transit insurance documentation, and gate pass processing.',
    phase: 'Phase 4 Module',
  },
  {
    id: '11',
    code: 'MICC',
    name: '11 MICC',
    adminGroup: 'ADMIN_C',
    group: 'C',
    groupTitle: 'C — ADMIN',
    description: 'Material Inspection and Clearance Certificate issuance by nodal authority upon site delivery.',
    phase: 'Phase 4 Module',
  },
  {
    id: '12',
    code: 'PB',
    name: '12 Progressive Bill',
    adminGroup: 'ADMIN_C',
    group: 'C',
    groupTitle: 'C — ADMIN',
    description: 'Progressive running account (RA) bill preparation, MB measurement verification, and statutory deductions.',
    phase: 'Phase 4 Module',
  },
  {
    id: '13',
    code: 'FB',
    name: '13 Final Bill',
    adminGroup: 'ADMIN_C',
    group: 'C',
    groupTitle: 'C — ADMIN',
    description: 'Final project reconciliation bill, no-claim certificate, CPG release processing, and financial closure.',
    phase: 'Phase 4 Module',
  },
];

export const STAGE_NAV_MAP: Record<string, string> = {
  '01': '/tenders',
  '02': '/loi-loa',
  '03': '/acceptance',
  '04': '/cpg-agreement',
  '05': '/gtp',
  '06': '/po',
  '07': '/inspection-call',
  '08': '/inspection-order',
  '09': '/jir',
  '10': '/di',
  '11': '/micc',
  '12': '/progressive-bill',
  '13': '/final-bill',
};

export const SIDEBAR_NAV_ITEMS = [
  {
    title: 'Active Modules',
    items: [
      { name: 'Dashboard', href: '/', icon: 'LayoutDashboard', active: true },
      { name: 'Projects', href: '/projects', icon: 'FolderKanban', active: true },
      { name: 'BOQ Management', href: '/boq', icon: 'ListTree', active: true },
    ],
  },
  {
    title: 'Project Workflow',
    items: [
      { name: '01 Tender', href: '/tenders', icon: 'FileSpreadsheet', stageId: '01', isFuture: false },
      { name: '02 LOI / LOA', href: '/loi-loa', icon: 'FileCheck', stageId: '02', isFuture: false },
      { name: '03 Acceptance', href: '/acceptance', icon: 'FileSignature', stageId: '03', isFuture: false },
      { name: '04 CPG + Agreement', href: '/cpg-agreement', icon: 'ShieldCheck', stageId: '04', isFuture: false },
      { name: '05 GTP', href: '/gtp', icon: 'Cpu', stageId: '05', isFuture: false },
      { name: '06 PO', href: '/po', icon: 'ShoppingCart', stageId: '06', isFuture: false },
      { name: '07 Inspection Call', href: '/inspection-call', icon: 'BellRing', stageId: '07', isFuture: false },
      { name: '08 Inspection Order', href: '/inspection-order', icon: 'ClipboardCheck', stageId: '08', isFuture: false },
      { name: '09 JIR / Inspection Report', href: '/jir', icon: 'FileBadge', stageId: '09', isFuture: false },
      { name: '10 DI / Dispatch Clearance', href: '/di', icon: 'Truck', stageId: '10', isFuture: false },
      { name: '11 MICC', href: '/micc', icon: 'Award', stageId: '11', isFuture: false },
      { name: '12 Progressive Bill', href: '/progressive-bill', icon: 'Receipt', stageId: '12', isFuture: false },
      { name: '13 Final Bill', href: '/final-bill', icon: 'CheckCheck', stageId: '13', isFuture: false },
    ],
  },
  {
    title: 'System & Records',
    items: [
      { name: 'Documents', href: '#', icon: 'FileText', isFuture: true, badge: 'Future Phases' },
      { name: 'Reports', href: '#', icon: 'BarChart3', isFuture: true, badge: 'Future Phases' },
      { name: 'Settings', href: '#', icon: 'Settings', isFuture: true, badge: 'Future Phases' },
    ],
  },
];
