import { Project, PendingAction, Activity, DocumentPlaceholder, NotificationItem, ProjectWorkflowState } from '@/types';
import { WORKFLOW_STAGES } from './constants';

function generateWorkflow(completedUpToStageId: string, inProgressStageId?: string): ProjectWorkflowState[] {
  return WORKFLOW_STAGES.map((s) => {
    const stageNum = parseInt(s.id, 10);
    const completedNum = parseInt(completedUpToStageId, 10);
    const inProgNum = inProgressStageId ? parseInt(inProgressStageId, 10) : completedNum + 1;

    let status: 'Completed' | 'In Progress' | 'Not Started' = 'Not Started';
    let completedAt: string | undefined = undefined;

    if (stageNum <= completedNum) {
      status = 'Completed';
      completedAt = '2024-03-15';
    } else if (stageNum === inProgNum) {
      status = 'In Progress';
    }

    return {
      stageId: s.id,
      status,
      adminGroup: s.adminGroup,
      assignedUser: s.adminGroup === 'ADMIN_A' ? 'Admin A Team' : s.adminGroup === 'ADMIN_B' ? 'Admin B Team' : 'Admin C Team',
      completedAt,
      updatedAt: '2024-05-10',
      notes: status === 'In Progress' ? `Administrative processing currently active for ${s.name}.` : undefined,
    };
  });
}

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'PRJ-2024-001',
    name: 'Bongaigaon Medical College 33kV Substation',
    code: 'UK-BGA-33KV',
    client: 'Assam Power Distribution Co. Ltd. (APDCL)',
    department: 'Chief General Manager (PP&D)',
    location: 'Bongaigaon, Assam',
    tenderRef: 'APDCL/CGM(PP&D)/MED-COLL/33KV/2023/14',
    contractValue: '₹ 28.40 Cr',
    startDate: '2023-11-10',
    expectedCompletion: '2025-05-30',
    projectManager: 'Er. Sanjib Baruah',
    status: 'In Progress',
    currentStageId: '06',
    currentStageName: '06 PO',
    stageGroup: 'B',
    remarks: 'Turnkey 33/11kV Substation including 2x10MVA transformers and associated terminal equipment.',
    createdAt: '2023-11-05',
    updatedAt: '2024-05-14',
    workflow: generateWorkflow('05', '06'),
  },
  {
    id: 'PRJ-2024-002',
    name: 'Demo 33kV Infrastructure Project',
    code: 'UK-INFRA-33KV-02',
    client: 'State Electricity Board Infrastructure Wing',
    department: 'Transmission & Distribution Circle',
    location: 'Guwahati Outer Ring, Assam',
    tenderRef: 'SEB/INFRA/TND-89/2023',
    contractValue: '₹ 42.50 Cr',
    startDate: '2023-08-15',
    expectedCompletion: '2025-02-28',
    projectManager: 'Er. Dilip Hazarika',
    status: 'Attention Required',
    currentStageId: '08',
    currentStageName: '08 Inspection Order',
    stageGroup: 'B',
    remarks: 'Pending inspector deputation confirmation from client regional quality circle for 33kV isolators.',
    createdAt: '2023-08-10',
    updatedAt: '2024-05-15',
    workflow: generateWorkflow('07', '08'),
  },
  {
    id: 'PRJ-2024-003',
    name: 'Demo Transformer Supply Project',
    code: 'UK-TRF-SUPPLY-03',
    client: 'Power Distribution Corporation Limited',
    department: 'Central Procurement Agency',
    location: 'Tezpur Central Stores, Assam',
    tenderRef: 'PDCL/PROC/TRF-132/2023/09',
    contractValue: '₹ 19.80 Cr',
    startDate: '2023-12-01',
    expectedCompletion: '2024-11-30',
    projectManager: 'Er. Pranab Kalita',
    status: 'In Progress',
    currentStageId: '10',
    currentStageName: '10 DI / Dispatch Clearance',
    stageGroup: 'C',
    remarks: 'Material factory testing completed successfully; awaiting formal dispatch instruction authorization.',
    createdAt: '2023-11-25',
    updatedAt: '2024-05-12',
    workflow: generateWorkflow('09', '10'),
  },
  {
    id: 'PRJ-2024-004',
    name: 'Lower Subansiri 220kV Transmission Bay Package',
    code: 'UK-LS-220KV-04',
    client: 'National Hydroelectric Power Corp (NHPC)',
    department: 'Contracts & Electrical Projects',
    location: 'Gerukamukh, Dhemaji',
    tenderRef: 'NHPC/LS/EL-220/PKG-B/2023',
    contractValue: '₹ 56.10 Cr',
    startDate: '2023-04-01',
    expectedCompletion: '2024-09-15',
    projectManager: 'Er. Rituraj Sarma',
    status: 'In Progress',
    currentStageId: '11',
    currentStageName: '11 MICC',
    stageGroup: 'C',
    remarks: 'Site delivery completed for bay structures; joint verification scheduled for MICC endorsement.',
    createdAt: '2023-03-20',
    updatedAt: '2024-05-11',
    workflow: generateWorkflow('10', '11'),
  },
  {
    id: 'PRJ-2024-005',
    name: 'Guwahati Smart Grid Metering & Substation Automation',
    code: 'UK-GW-METER-05',
    client: 'Smart City Development Agency Ltd.',
    department: 'Urban Grid Modernization Wing',
    location: 'Guwahati Metro, Assam',
    tenderRef: 'GSCDL/SMART/GRID-04/2023',
    contractValue: '₹ 34.20 Cr',
    startDate: '2024-01-15',
    expectedCompletion: '2025-07-31',
    projectManager: 'Er. Anupam Das',
    status: 'In Progress',
    currentStageId: '05',
    currentStageName: '05 GTP',
    stageGroup: 'B',
    remarks: 'GTP submissions under technical review by nodal consulting engineer.',
    createdAt: '2024-01-05',
    updatedAt: '2024-05-13',
    workflow: generateWorkflow('04', '05'),
  },
  {
    id: 'PRJ-2024-006',
    name: 'Dibrugarh Feeder Segregation & Reconductoring',
    code: 'UK-DIB-FDR-06',
    client: 'Assam Power Distribution Co. Ltd. (APDCL)',
    department: 'Upper Assam Electrical Zone',
    location: 'Dibrugarh, Assam',
    tenderRef: 'APDCL/UAZ/FDR-SEG/2023/88',
    contractValue: '₹ 22.75 Cr',
    startDate: '2023-06-20',
    expectedCompletion: '2024-10-30',
    projectManager: 'Er. Sanjib Baruah',
    status: 'Attention Required',
    currentStageId: '07',
    currentStageName: '07 Inspection Call',
    stageGroup: 'B',
    remarks: 'Factory ready notice submitted; client quality wing rescheduling inspection due to monsoon transit alerts.',
    createdAt: '2023-06-10',
    updatedAt: '2024-05-14',
    workflow: generateWorkflow('06', '07'),
  },
  {
    id: 'PRJ-2024-007',
    name: 'Tezpur Industrial Substation 33/11kV Package',
    code: 'UK-TEZ-IND-07',
    client: 'Assam Industrial Development Corp (AIDC)',
    department: 'Infrastructure Development Division',
    location: 'Balipara Industrial Park, Tezpur',
    tenderRef: 'AIDC/BALIPARA/SUBSTATION/2023',
    contractValue: '₹ 15.60 Cr',
    startDate: '2023-09-01',
    expectedCompletion: '2024-12-15',
    projectManager: 'Er. Dilip Hazarika',
    status: 'In Progress',
    currentStageId: '09',
    currentStageName: '09 JIR / Inspection Report',
    stageGroup: 'B',
    remarks: 'Joint inspection completed; pending formal signed JIR booklet copy.',
    createdAt: '2023-08-25',
    updatedAt: '2024-05-08',
    workflow: generateWorkflow('08', '09'),
  },
  {
    id: 'PRJ-2024-008',
    name: 'Silchar 132kV Line Terminal Augmentation',
    code: 'UK-SIL-132KV-08',
    client: 'Assam Electricity Grid Corp Ltd. (AEGCL)',
    department: 'Lower Assam Transmission Circle',
    location: 'Panchgram, Barak Valley',
    tenderRef: 'AEGCL/MD/LATC/TERM-AUG/2023',
    contractValue: '₹ 38.90 Cr',
    startDate: '2023-02-10',
    expectedCompletion: '2024-04-30',
    projectManager: 'Er. Rituraj Sarma',
    status: 'Completed',
    currentStageId: '13',
    currentStageName: '13 Final Bill',
    stageGroup: 'C',
    remarks: 'Full contract completed and commissioned; final billing settlement finalized.',
    createdAt: '2023-01-20',
    updatedAt: '2024-05-02',
    workflow: generateWorkflow('13'),
  },
  {
    id: 'PRJ-2024-009',
    name: 'Nagaon Solar Park Grid Interconnection Package',
    code: 'UK-NAG-SOLAR-09',
    client: 'State Renewable Energy Agency',
    department: 'Grid Evacuation & Solar Wing',
    location: 'Nagaon, Assam',
    tenderRef: 'SREA/NGN/SOLAR-EVAC/2023/03',
    contractValue: '₹ 26.50 Cr',
    startDate: '2023-05-15',
    expectedCompletion: '2024-06-30',
    projectManager: 'Er. Pranab Kalita',
    status: 'Completed',
    currentStageId: '13',
    currentStageName: '13 Final Bill',
    stageGroup: 'C',
    remarks: 'Interconnection commissioned successfully; CPG release processed.',
    createdAt: '2023-05-01',
    updatedAt: '2024-05-04',
    workflow: generateWorkflow('13'),
  },
  {
    id: 'PRJ-2024-010',
    name: 'Jorhat Town Power Reliability Underground Cabling',
    code: 'UK-JOR-UG-10',
    client: 'Urban Development & Poverty Alleviation',
    department: 'City Electrical Infrastructure Board',
    location: 'Jorhat Town, Assam',
    tenderRef: 'UDD/JRH/CBL-UG/2022/99',
    contractValue: '₹ 47.30 Cr',
    startDate: '2022-10-01',
    expectedCompletion: '2024-03-31',
    projectManager: 'Er. Dilip Hazarika',
    status: 'Completed',
    currentStageId: '13',
    currentStageName: '13 Final Bill',
    stageGroup: 'C',
    remarks: 'Underground conversion fully operational and handed over.',
    createdAt: '2022-09-15',
    updatedAt: '2024-04-10',
    workflow: generateWorkflow('13'),
  },
  {
    id: 'PRJ-2024-011',
    name: 'Barpeta 33/11kV Substation & Switchyard Expansion',
    code: 'UK-BAR-33KV-11',
    client: 'Assam Power Distribution Co. Ltd. (APDCL)',
    department: 'Central Assam Projects Division',
    location: 'Barpeta Road, Assam',
    tenderRef: 'APDCL/CAPD/BAR-EXP/2022/11',
    contractValue: '₹ 17.20 Cr',
    startDate: '2022-11-15',
    expectedCompletion: '2024-02-28',
    projectManager: 'Er. Sanjib Baruah',
    status: 'Completed',
    currentStageId: '13',
    currentStageName: '13 Final Bill',
    stageGroup: 'C',
    remarks: 'All progressive bills and final reconciliation closed.',
    createdAt: '2022-11-01',
    updatedAt: '2024-03-25',
    workflow: generateWorkflow('13'),
  },
  {
    id: 'PRJ-2024-012',
    name: 'Golaghat Rural High Voltage Feeder Extension',
    code: 'UK-GOL-RUR-12',
    client: 'Assam Power Distribution Co. Ltd. (APDCL)',
    department: 'Rural Electrification Monitoring Cell',
    location: 'Golaghat Rural Belt, Assam',
    tenderRef: 'APDCL/REM/GLG-FDR/2024/01',
    contractValue: '₹ 31.00 Cr',
    startDate: '2024-03-01',
    expectedCompletion: '2025-08-31',
    projectManager: 'Er. Anupam Das',
    status: 'Attention Required',
    currentStageId: '04',
    currentStageName: '04 CPG + Agreement',
    stageGroup: 'A',
    remarks: 'Original bank guarantee format amendment requested by client finance directorate.',
    createdAt: '2024-02-18',
    updatedAt: '2024-05-15',
    workflow: generateWorkflow('03', '04'),
  },
];

export const INITIAL_PENDING_ACTIONS: PendingAction[] = [
  {
    id: 'ACT-001',
    projectId: 'PRJ-2024-002',
    project: 'Demo 33kV Infrastructure Project',
    projectCode: 'UK-INFRA-33KV-02',
    action: 'Follow up on Inspection Order for 33kV Isolators & CTs',
    priority: 'High',
    dueDate: '2024-05-18',
    status: 'Pending',
    category: 'Inspection Management',
  },
  {
    id: 'ACT-002',
    projectId: 'PRJ-2024-012',
    project: 'Golaghat Rural High Voltage Feeder Extension',
    projectCode: 'UK-GOL-RUR-12',
    action: 'Submit revised CPG bank guarantee text as per client legal note',
    priority: 'High',
    dueDate: '2024-05-19',
    status: 'Pending',
    category: 'Contract Guarantee',
  },
  {
    id: 'ACT-003',
    projectId: 'PRJ-2024-003',
    project: 'Demo Transformer Supply Project',
    projectCode: 'UK-TRF-SUPPLY-03',
    action: 'Obtain written Dispatch Instruction (DI) from CE Procurement',
    priority: 'High',
    dueDate: '2024-05-20',
    status: 'In Progress',
    category: 'Dispatch Clearance',
  },
  {
    id: 'ACT-004',
    projectId: 'PRJ-2024-001',
    project: 'Bongaigaon Medical College 33kV Substation',
    projectCode: 'UK-BGA-33KV',
    action: 'Upload counter-signed Purchase Order for Vacuum Circuit Breakers',
    priority: 'Medium',
    dueDate: '2024-05-22',
    status: 'Pending',
    category: 'Administrative Entry',
  },
  {
    id: 'ACT-005',
    projectId: 'PRJ-2024-005',
    project: 'Guwahati Smart Grid Metering & Substation Automation',
    projectCode: 'UK-GW-METER-05',
    action: 'GTP technical compliance compliance matrix sign-off',
    priority: 'Medium',
    dueDate: '2024-05-25',
    status: 'Pending',
    category: 'Engineering & GTP',
  },
  {
    id: 'ACT-006',
    projectId: 'PRJ-2024-006',
    project: 'Dibrugarh Feeder Segregation & Reconductoring',
    projectCode: 'UK-DIB-FDR-06',
    action: 'Reschedule factory inspection with TPI agency',
    priority: 'Low',
    dueDate: '2024-05-28',
    status: 'Pending',
    category: 'Quality Assurance',
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'HIST-001',
    projectId: 'PRJ-2024-002',
    user: 'Prastab Raaj (Project Executive)',
    action: 'Status flagged to Attention Required due to inspection order delay',
    timestamp: '2024-05-15 11:20 AM',
    environment: 'DEMO',
    details: 'Inspection call raised on 28th April; inspector deputation pending from client end.',
  },
  {
    id: 'HIST-002',
    projectId: 'PRJ-2024-012',
    user: 'Prastab Raaj (Project Executive)',
    action: 'Administrative entry updated: CPG bank confirmation query logged',
    timestamp: '2024-05-15 09:45 AM',
    environment: 'DEMO',
    details: 'Bank format requested with indemnity clause amendment.',
  },
  {
    id: 'HIST-003',
    projectId: 'PRJ-2024-001',
    user: 'Er. Sanjib Baruah (Project Manager)',
    action: 'Stage advanced to 06 PO following GTP formal approval',
    timestamp: '2024-05-14 04:15 PM',
    environment: 'DEMO',
    details: 'All technical drawings cleared by APDCL design office.',
  },
  {
    id: 'HIST-004',
    projectId: 'PRJ-2024-003',
    user: 'Prastab Raaj (Project Executive)',
    action: 'Routine test certificate submitted for dispatch clearance endorsement',
    timestamp: '2024-05-12 02:30 PM',
    environment: 'DEMO',
    details: 'JIR clearance endorsed; waiting for DI authorization number.',
  },
  {
    id: 'HIST-005',
    projectId: 'PRJ-2024-004',
    user: 'Er. Rituraj Sarma (Project Manager)',
    action: 'Consignment delivery receipts acknowledged by site engineer',
    timestamp: '2024-05-11 11:00 AM',
    environment: 'DEMO',
    details: 'Challan and road permits verified at Gerukamukh store yard.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    title: 'Inspection Order Attention Needed',
    message: 'Demo 33kV Infrastructure Project has pending inspector assignment (Overdue 4 days).',
    timestamp: '15 mins ago',
    read: false,
    type: 'alert',
    link: '/projects/PRJ-2024-002',
  },
  {
    id: 'NOTIF-02',
    title: 'CPG Bank Amendment',
    message: 'Golaghat Rural High Voltage Feeder Extension requires CPG draft update.',
    timestamp: '2 hours ago',
    read: false,
    type: 'alert',
    link: '/projects/PRJ-2024-012',
  },
  {
    id: 'NOTIF-03',
    title: 'PO Stage Update',
    message: 'Bongaigaon Medical College 33kV Substation moved to Stage 06 (PO).',
    timestamp: '1 day ago',
    read: true,
    type: 'update',
    link: '/projects/PRJ-2024-001',
  },
];

export const INITIAL_DOCUMENTS: DocumentPlaceholder[] = [
  {
    id: 'DOC-001',
    projectId: 'PRJ-2024-001',
    name: 'Notice_Inviting_Tender_NIT_14_2023.pdf',
    code: 'DOC-TND-001',
    category: 'Tender & Bid Documents',
    fileType: 'PDF',
    fileSize: '4.8 MB',
    uploadedBy: 'P. Raaj',
    uploadDate: '2023-11-12',
    status: 'Verified',
  },
  {
    id: 'DOC-002',
    projectId: 'PRJ-2024-001',
    name: 'Letter_of_Award_LOA_APDCL_492.pdf',
    code: 'DOC-LOA-002',
    category: 'Contracts & Agreements',
    fileType: 'PDF',
    fileSize: '1.2 MB',
    uploadedBy: 'P. Raaj',
    uploadDate: '2023-12-05',
    status: 'Verified',
  },
  {
    id: 'DOC-003',
    projectId: 'PRJ-2024-001',
    name: 'CPG_Bank_Guarantee_BG7881092.pdf',
    code: 'DOC-CPG-003',
    category: 'Bank Guarantees',
    fileType: 'PDF',
    fileSize: '890 KB',
    uploadedBy: 'P. Raaj',
    uploadDate: '2023-12-20',
    status: 'Verified',
  },
  {
    id: 'DOC-004',
    projectId: 'PRJ-2024-001',
    name: 'GTP_Single_Line_Diagram_Rev3.dwg',
    code: 'DOC-GTP-004',
    category: 'Engineering Drawings',
    fileType: 'DWG',
    fileSize: '14.2 MB',
    uploadedBy: 'Er. S. Baruah',
    uploadDate: '2024-02-18',
    status: 'Verified',
  },
  {
    id: 'DOC-005',
    projectId: 'PRJ-2024-001',
    name: 'Purchase_Order_Draft_VCB_Panels.xlsx',
    code: 'DOC-PO-005',
    category: 'Procurement',
    fileType: 'XLSX',
    fileSize: '420 KB',
    uploadedBy: 'P. Raaj',
    uploadDate: '2024-05-14',
    status: 'Pending Review',
  },
];
